version: '3.7'
services:
  app:
    container_name: encryptor-app
    build:
      context: .
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules:cached
    env_file:
      - .env
    ports:
      - '3000:3000'

